#!/bin/bash
# Sould be run as user

if [[ $HOSTNAME == "olympe" ]]
then
    #variables
    OPTS="-alrv --bwlimit=1M"
    SRC=/media/HomeStorage/_backups
    DEST=/media/ColdStorage/_backups
#     DEST=/media/manu/Storage/_backups

    if [ -d $DEST ] ; then
        if [ -d $SRC ] ; then
            ##############
            # W1
            ##############
            #with delete propagation
            rsync $OPTS --delete $SRC/    $DEST
        else
            echo "Folder source not mounted"
        fi
    else
        echo "Folder dest not mounted"
    fi
else 
    echo "Wrong environment"
fi
