#! /bin/awk 
 
BEGIN {
  IGNORECASE=1
  FS=","
  split(ARGV[2],a,"=");
  bb=tolower(a[1])"[ ]*="
}


#$0 ~  bb {for(i=1;i<NF;i=i+2){if($i~bb){ print " ",a[1]"="a[2]; }else{  gsub(" ","",$i); print " ",$i,"=",$(i+1)}  }   }
#$0 !~ b {print}

$0 ~ bb {
	for(i=1;i<=NF;i=i+1){
		 buff=$i;
		 if($i~"!" ){ 
			split($i,c,"!");
			 print "!"c[2]; buff=c[1]
		}
    		if(buff~bb){ 
			print "  "a[1]"="a[2] 
		 } else{ 
			if(length(buff)>0){ 
				gsub(" ","",buff);		
				print "  "buff
			}
		}
	}
    }
$0 !~ bb {print}
#


#$0 ~ bb {for(i=1;i<=NF;i=i+1){ buff=$i;   if($i~"!" ){ split($i,c,"!"); print "!"c[2]; buff=c[1]}    if(buff~bb){ print "++"a[1]"="a[2]  } else{ if(length(buff)>0){ gsub(" ","",buff);  print "--"$i}   }    }  }
#$0 !~ bb {print "//"$0}
#/SPCH/ {print "|"$0"|"}
