#!/bin/bash

#!!! Should not be run as root (for now)


# Getting the directory where this script is stored
path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "USER: " $USERNAME $USER
echo "PATH: " $path
# Going to user home directory
cd ~

# Moving existing dofiles to a backup folder
BKP_FOLDER=_bkp_dotfiles
echo "Backup Folder: $BKP_FOLDER"
mkdir -p $BKP_FOLDER 
mv .xinitrc .xsessionrc .bashrc .bash_logout .bash_profile .ctags .vimrc .vim .gitconfig .profile $BKP_FOLDER
# Moving existing dotconfig to a backup folder
mv .config/Templates .config/xfce4 .config/Thunar $BKP_FOLDER
# Moving existing dotfolders to a backup folder
mv .themes .fonts $BKP_FOLDER

# Linking dotfiles
ln -s $path/dotfiles/xinitrc .xinitrc
ln -s $path/dotfiles/xsessionrc .xsessionrc
ln -s $path/dotfiles/bashrc_user.bash .bashrc
ln -s $path/dotfiles/bash_profile.bash .bash_profile
ln -s $path/dotfiles/bash_logout .bash_logout
ln -s $path/dotfiles/ctags .ctags
ln -s $path/dotfiles/vimrc .vimrc
ln -s $path/dotfiles/profile .profile
# Linking dotfolders
ln -s $path/dotfiles/vim .vim
# Linking .config folders
mkdir -p .config
ln -s $path/dotconfig/xfce4 .config/xfce4
ln -s $path/dotconfig/Thunar .config/Thunar



if [ $HOSTNAME == 'work' ]
then
    echo "Work"
    ln -s $path/dotfiles/gitconfig-work .gitconfig
elif [ $HOSTNAME == 'work' ]
then
    echo "Work"
    ln -s $path/dotfiles/gitconfig-work .gitconfig
else
    ln -s $path/dotfiles/gitconfig .gitconfig
fi
# Fonts
ln -s $path/fonts .fonts
fc-cache -vf ~/.fonts

# templates
ln -s $path/profiles/templates .config/Templates

# look
ln -s $path/look/themes .themes
