#!/bin/bash

if [[ `git remote 2>/dev/null|wc -l` == 0 ]] 
then
    git init
    git git remote add origin git@github:elmanuelito/config.git
    git pull origin master
#     git clone git@github:elmanuelito/config.git .
fi

git pull origin master
