#!/bin/bash

if [[ `git remote 2>/dev/null|wc -l` == 0 ]] 
then
    git init
    git remote add origin git@github:ebranlard/config.git
    git config core.fileMode false
    git pull origin master
fi

git pull origin master
