#!/bin/bash
# Sould be run as user

if [[ `cat /etc/hostname` == "work" ]]
then
    #variables
    OPTS="-av"
    DEST=/media/Storage2

    ##############
    # DATAWIN
    ##############
    SRC=/mnt/DataWin
    #without deletion
    rsync $OPTS $SRC/Cursus/ $DEST/Cursus/
    rsync $OPTS $SRC/Pictures/ $DEST/Pictures/
    #with delete propagation
    rsync $OPTS --delete $SRC/Admin/ $DEST/Admin/
    rsync $OPTS --delete $SRC/Geekeries/ $DEST/Geekeries/
    rsync $OPTS --delete $SRC/Projects/ $DEST/Projects/
    rsync $OPTS --delete $SRC/Work/ $DEST/Work/

    ##############
    # Linux
    ##############
    SRC=/home/manu
    #with delete propagation
    rsync $OPTS --delete $SRC/Config/ "$DEST/Config-Work/"
else 
    echo "Wrong environment"
fi
