#!/bin/bash
# Sould be run as user

if [[ $HOSTNAME == "olympe" ]]
then
    #variables
    OPTS="-alrv"
    DEST=/media/HomeStorage/_backups
    SRC=/media/WorkStorage/_backups

    if [ -d $DEST ] ; then
        if [ -d $SRC ] ; then
            ##############
            # W1
            ##############
            #with delete propagation
            rsync $OPTS --delete $SRC/W1/    $DEST/W1
        else
            echo "Folder source not mounted"
        fi
    else
        echo "Folder dest not mounted"
    fi
else 
    echo "Wrong environment"
fi
