#!/usr/bin/env python
# job-log: displays the log file of the last job - otherwise takes a node name as argument
#
# E. Branlard - August 2014
# 
# usage: job-log [node]

import sys
import os


# if __name__ == "__main__":

user='ebra'

# --------------------------------------------------------------------------------
# --- Getting job PBS id
# --------------------------------------------------------------------------------
cmd="qstat -u %s|awk 'NR>5'|awk '{print $1}'|awk -F. '{print $1}'"%user
print(cmd)
jobpbsid = os.popen(cmd).read().split('\n')
print(jobpbsid)

# number of jobs
n_jobs=len(jobpbsid)-1


if (len(sys.argv)>1):
    main_node=sys.argv[1]
else:
    if n_jobs<=1:
        print('No job')
        sys.exit(-1)

    else:
        id=jobpbsid[n_jobs-1]
        print (id)
        cmd="qstat -n %s |awk -F- 'NR > 6 {print $0}'|xargs"%id
        cpu_list = os.popen(cmd).read().replace(' ','').replace('\n','').split('+')
        if cpu_list[0]=='--':
            main_node='--'
        else:
            nodes=list(set([int(x[2:5]) for x in cpu_list]))
            main_node=cpu_list[0][0:2]+"%03d"%nodes[0]
            if cpu_list[0][0]=='j':
                # hack for jess (nodes above change order due to set)
                main_node=cpu_list[0][0:5]




cmd="ssh %s@%s ls /scratch/ebra/*/sim_*/*.log"%(user,main_node)
print(cmd)
logfile=os.popen(cmd).read().replace('\n','')
print(logfile)

if len(logfile)>0:
    cmd="vim 'scp://%s@%s/%s'"%(user,main_node,logfile)
    print(cmd)
    os.system(cmd)

        
