#!/bin/bash

machines=(`qstat -nu $USER|awk 'NR>6'|awk 'NR % 2 ' |awk '{print $1}'|awk -F+ '{print $1}'`); 
jobpbsid=(`qstat -nu $USER|awk 'NR>5'|awk 'NR % 2 ' |awk '{print $1}'|awk -F. '{print $1}'`); 
jobnames=(`qstat -nu $USER|awk 'NR>5'|awk 'NR % 2 ' |awk '{print $4}'`); 
runtimes=(`qstat -nu $USER|awk 'NR>5'|awk 'NR % 2 ' |awk '{print $11}'`); 

n=`expr ${#machines[@]} - 1`

for i in `seq 0 $n`
do 
    machine=${machines[$i]}
    echo "-----------------------------------------------------------------------------"
    echo "NODE: $machine JOB: ${jobnames[$i]} - PID:${jobpbsid[$i]} - UP:${runtimes[$i]}"
    echo "-----------------------------------------------------------------------------"
    ssh ebra@$machine 'tail -n 20 /scratch/ebra/*/sim_*/*.log'

done
