#! /bin/bash

if [ $# -eq 0 ]
then 
	Files=*.pdf
        Files="$Files"
else
	l=$@
        Buff=""
        First=''
        for i in $l
        do
            if [ ! `echo $i |grep -E "[.][a-zA-Z]{3,4}$"` = "" ] 
            then
                    File="$Buff $i"
                    Buff=""
                    First=""
                    File2=`echo $File|tr ' ' '_'`
                    #
                    if [ $File != $File2 ]
                    then
                            mv "$File" $File2
                    fi
                    #
                    Files="$Files $File2"
           else
                if [ -z ${First} ] 
                then
                        Buff="$i"
                        First="no"
                else
                        Buff="$Buff $i"
                fi
           fi
           
        done
#        echo $Files
fi

FileOut=`echo $Files|grep -Eo "^[a-Z0-9\_ -]*[.]"|tr '_' ' '`"Bind.pdf"

echo $FileOut

pdftk $Files cat output "$FileOut"

