#!/usr/bin/python

import os, string

marker = 0
marker2 = 0
orderlist = []
a = open( 'playlists.xml', 'r' )
if not os.path.exists("playlists"):
    os.makedirs("playlists")
os.chdir("playlists")
z = open( 'order_file', 'w' )
for line in a.xreadlines():
    if marker == 1:
        if line.find('<location>') != -1 and line.rfind('</location>') != -1:
            line = line[line.find('<location>')+10:]
            line = line[:line.find('</location>')]
            line = string.replace( line, '&amp;', '&' )
            if marker2 == 0:
                m = open( name+'.playlist', 'w' )
                z.write(name+'\n')
                marker2 = 1
            m.write(line+'\n')
        elif line.find('</playlist>') != -1:
            if marker2 == 0:
                continue
            m.write('EOF\n')
            m.write('random_enabled=B: False\n')
            m.write('random_mode=S: track\n')
            m.write('repeat_enabled=B: False\n')
            m.write('repeat_mode=S: playlist\n')
            m.write('dynamic_enabled=B: False\n')
            m.write('current_pos=I: -1\n')
            m.write('name=U: '+name+'\n')
            m.write('_is_custom=B: True\n')
            m.write('_needs_save=B: False\n')
            m.close()
            marker = 0
            marker2 = 0
    elif line.find('<playlist name="') != -1:
        if line.rfind('/>') == -1:
            line = line[line.find('<playlist name="')+16:]
            line = line[:line.find('"')]
            line = string.replace( line, '&amp;', '&' )
            name = line
            marker = 1
a.close()
z.write('EOF\n')
z.close()
