#!/bin/sh
#############################################################
# :
#############################################################
# Description :
# Written by : Emmanuel Branlard
# Date : 
# Dependencies : 
# License : Feel free to modify and adapt it
# Note : 
#     pdftk file.pdf burst
#############################################################
$@
/bin/bash
